# Generated by Django 5.1.3 on 2024-11-26 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_Title', models.CharField(max_length=100)),
                ('task_Description', models.TextField()),
                ('is_completed', models.BooleanField(default=False)),
                ('assign_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('category', models.ManyToManyField(to='Category.category_model')),
            ],
        ),
    ]
